/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthMedicationsIndexRouteImport } from './routes/_auth/medications/index'
import { Route as AuthMedicationsIdRouteImport } from './routes/_auth/medications/$id'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMedicationsIndexRoute = AuthMedicationsIndexRouteImport.update({
  id: '/medications/',
  path: '/medications/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMedicationsIdRoute = AuthMedicationsIdRouteImport.update({
  id: '/medications/$id',
  path: '/medications/$id',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/medications/$id': typeof AuthMedicationsIdRoute
  '/medications/': typeof AuthMedicationsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/': typeof AuthIndexRoute
  '/medications/$id': typeof AuthMedicationsIdRoute
  '/medications': typeof AuthMedicationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/medications/$id': typeof AuthMedicationsIdRoute
  '/_auth/medications/': typeof AuthMedicationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/login' | '/not-found' | '/medications/$id' | '/medications/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/not-found' | '/' | '/medications/$id' | '/medications'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/not-found'
    | '/_auth/'
    | '/_auth/medications/$id'
    | '/_auth/medications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  NotFoundRoute: typeof NotFoundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/medications/': {
      id: '/_auth/medications/'
      path: '/medications'
      fullPath: '/medications/'
      preLoaderRoute: typeof AuthMedicationsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/medications/$id': {
      id: '/_auth/medications/$id'
      path: '/medications/$id'
      fullPath: '/medications/$id'
      preLoaderRoute: typeof AuthMedicationsIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthMedicationsIdRoute: typeof AuthMedicationsIdRoute
  AuthMedicationsIndexRoute: typeof AuthMedicationsIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthMedicationsIdRoute: AuthMedicationsIdRoute,
  AuthMedicationsIndexRoute: AuthMedicationsIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  NotFoundRoute: NotFoundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
