/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as MedicationsIndexRouteImport } from './routes/medications/index'
import { Route as MedicationsIdRouteImport } from './routes/medications/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicationsIndexRoute = MedicationsIndexRouteImport.update({
  id: '/medications/',
  path: '/medications/',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicationsIdRoute = MedicationsIdRouteImport.update({
  id: '/medications/$id',
  path: '/medications/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/medications/$id': typeof MedicationsIdRoute
  '/medications/': typeof MedicationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/medications/$id': typeof MedicationsIdRoute
  '/medications': typeof MedicationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/medications/$id': typeof MedicationsIdRoute
  '/medications/': typeof MedicationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/login' | '/not-found' | '/medications/$id' | '/medications/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/not-found' | '/medications/$id' | '/medications'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/not-found'
    | '/medications/$id'
    | '/medications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  NotFoundRoute: typeof NotFoundRoute
  MedicationsIdRoute: typeof MedicationsIdRoute
  MedicationsIndexRoute: typeof MedicationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medications/': {
      id: '/medications/'
      path: '/medications'
      fullPath: '/medications/'
      preLoaderRoute: typeof MedicationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medications/$id': {
      id: '/medications/$id'
      path: '/medications/$id'
      fullPath: '/medications/$id'
      preLoaderRoute: typeof MedicationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  NotFoundRoute: NotFoundRoute,
  MedicationsIdRoute: MedicationsIdRoute,
  MedicationsIndexRoute: MedicationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
